DROP TABLE SWING_MEMBER;
CREATE TABLE SWING_MEMBER(
     SWNUM  VARCHAR2(20)PRIMARY KEY 
    ,SWNAME VARCHAR2(20) NOT NULL
    ,SWID   VARCHAR2(20)
    ,SWPW   VARCHAR2(20) NOT NULL   
    ,DELETEYN VARCHAR2(1) NOT NULL
    ,INSERTDATE DATE
    ,UPDATEDATE DATE
);  

-- SYS_C0011097
SELECT  TABLE_NAME, INDEX_NAME, COLUMN_NAME
FROM    USER_IND_COLUMNS
WHERE   TABLE_NAME IN ('SWING_MEMBER');

SELECT  /*+ INDEX_DESC(SYS_C0011097)*/											
        NVL(MAX(SUBSTR(A.SWNUM, -4)), 0) + 1 COMMNO	
FROM    SWING_MEMBER A;

SELECT * FROM SWING_MEMBER;



SELECT											
			A.SWNUM						SWNUM		
			,A.SWNAME					SWNAME		
			,A.SWID						SWID		
			,A.SWPW						SWPW		
			,A.DELETEYN					DELETETN	
			,TO_CHAR(A.INSERTDATE,	'YYYY-MM-DD')		INSERTDATE		
			,TO_CHAR(A.UPDATEDATE,	'YYYY-MM-DD')		UPDATEDATE		
FROM												
				SWING_MEMBER  A					
WHERE DELETEYN = 'Y'								
ORDER BY 1 DESC;		

SELECT 								
       COUNT(A.SWNUM)  NCNT 			
	FROM 								
		  SWING_MEMBER 	A 				
	WHERE A.DELETEYN 	= 'Y'			
	AND   A.SWID 	  	= 'LOVE2'				
	AND   A.SWPW  		= 123456;   
    
    
    DROP TABLE SWING_MEMBER;
    CREATE TABLE SWING_MEMBER(
     SWNUM  VARCHAR2(20)PRIMARY KEY 
    ,SWNAME VARCHAR2(20) NOT NULL
    ,SWID   VARCHAR2(20)
    ,SWPW   VARCHAR2(20) NOT NULL   
    ,DELETEYN VARCHAR2(1) NOT NULL
    ,INSERTDATE DATE
    ,UPDATEDATE DATE
);  

DROP TABLE KBD_MEMBER;
CREATE TABLE KBD_MEMBER(
    KNUM VARCHAR2(20) PRIMARY KEY
    ,KNAME VARCHAR2(20) NOT NULL
    ,KID VARCHAR2(20)
    ,KPW VARCHAR2(20) NOT NULL
    ,KBIRTH VARCHAR2(10)
    ,KGENDER VARCHAR2(2)
    ,KTEL VARCHAR2(16)
    ,KHP VARCHAR2(16)
    ,KEMAIL VARCHAR2(200) NOT NULL
    ,KADDR VARCHAR2(300)
    ,KHOBBY VARCHAR2(2)
    ,KPHOTO VARCHAR2(200)
    ,KSKILL VARCHAR2(100)
    ,KJOB VARCHAR2(5)
    ,DELETEYN VARCHAR2(1)NOT NULL
    ,INSERTDATE DATE
    ,UPDATEDATE DATE
);

SELECT * FROM KBD_MEMBER;



DROP TABLE KBD_BOARD;
CREATE TABLE KBD_BOARD(
     BNUM  VARCHAR2(20)PRIMARY KEY NOT NULL 
    ,BSUBJECT VARCHAR2(20) NOT NULL
    ,BWRITER   VARCHAR2(20) NOT NULL
    ,BCONTENTS   VARCHAR2(20) 
    ,BPW   VARCHAR2(20)  
    ,DELETEYN VARCHAR2(1) NOT NULL
    ,INSERTDATE DATE
    ,UPDATEDATE DATE
);  

SELECT * FROM KBD_BOARD;




	
