/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-09-15 14:20:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.kbd.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import a.b.c.com.kbd.board.service.BoardService;
import a.b.c.com. kbd.board.service.BoardServiceImpl;
import a.b.c.com.kbd.board.vo.BoardVO;
import java.util.ArrayList;

public final class boardSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("a.b.c.com.kbd.board.vo.BoardVO");
    _jspx_imports_classes.add("a.b.c.com.kbd.board.service.BoardService");
    _jspx_imports_classes.add("a.b.c.com. kbd.board.service.BoardServiceImpl");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"   \r\n");
      out.write("	integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"   \r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("</script>\r\n");
      out.write("<title>글 전체조회</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	*{\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		/*text-align: center;*/\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div {\r\n");
      out.write("		margin: 50px 0px 0px 100px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	td, th{\r\n");
      out.write("		padding: 5px\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.tt{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script scr=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	window.onload = function () {\r\n");
      out.write("	 var isudType = $.urlParam('ISUD_TYPE');\r\n");
      out.write("	 if(isudType == 'D'){\r\n");
      out.write("		 boardUpdate('D');\r\n");
      out.write("	 }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$.urlParam = function(name){\r\n");
      out.write("	    var results = new RegExp('[\\?&amp;]' + name + '=([^&amp;#]*)').exec(window.location.href);\r\n");
      out.write("	    return results[1] || 0;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function boardUpdate(actionUpdate){\r\n");
      out.write("		\r\n");
      out.write("		if(actionUpdate == 'TEST'){\r\n");
      out.write("			console.log($(\"#boardUpdateForm\").serialize());\r\n");
      out.write("		} else {\r\n");
      out.write("			console.log(\"boardUpdate 진입 >>> : \" + actionUpdate);\r\n");
      out.write("			\r\n");
      out.write("			if('U' == actionUpdate) {\r\n");
      out.write("				var v1 = \"UOK\";\r\n");
      out.write("				document.boardUpdateForm.action=\"/testKbd/board?ISUD_TYPE=\"+v1;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if('D' == actionUpdate) {\r\n");
      out.write("				var v2 = \"DOK\";\r\n");
      out.write("				document.boardUpdateForm.action=\"/testKbd/board?ISUD_TYPE=DOK\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			document.boardUpdateForm.method=\"POST\";\r\n");
      out.write("			document.boardUpdateForm.enctype=\"applecation/x-www-form-urlencoded\";\r\n");
      out.write("			document.boardUpdateForm.submit();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function checkAction(actionName){\r\n");
      out.write("		console.log(\"actionName 진입 >>> : \" + actionName);\r\n");
      out.write("		\r\n");
      out.write("		if('I' == actionName) {\r\n");
      out.write("			location.href=\"/testKbd/kbd/board/board.html\";\r\n");
      out.write("		}\r\n");
      out.write("		if('SALL' == actionName){\r\n");
      out.write("			location.href=\"/testKbd/board?ISUD_TYPE=SALL\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 request.setCharacterEncoding("EUC-KR"); 
      out.write("\r\n");
      out.write("SELECT\r\n");
      out.write("\r\n");

	Object obj = request.getAttribute("aListS");
	if(obj == null) return;
	
	ArrayList<BoardVO> aList = (ArrayList<BoardVO>)obj;
	int nCnt = aList.size();
	out.println(":::: 조건 조회 >>> : " + nCnt + "건");
	
	String bnum="";
	String bsubject="";
	String bwriter="";
	String bpw="";
	String bmemo="";
	String bphoto="";
	String deleteyn="";
	String insertdate="";
	String updatedate="";
	
	if(nCnt == 1) {
		BoardVO bvo = aList.get(0);
		
		bnum = bvo.getBnum();
		bsubject = bvo.getBsubject();
		bwriter = bvo.getBwriter();
		bpw = bvo.getBpw();
		bmemo = bvo.getBmemo();
		bphoto = bvo.getBphoto();
		deleteyn = bvo.getDeleteyn();
		insertdate = bvo.getInsertdate();
		updatedate = bvo.getUpdatedate();
	}

      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<div>\r\n");
      out.write("<form name=\"boardUpdateForm\" id=\"boardUpdateForm\">\r\n");
      out.write("<table boarder=\"1\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">\r\n");
      out.write("	\r\n");
      out.write("		<font size=\"4\" style=\"color:blue;\">게시판 글 수정 && 삭제</font>\r\n");
      out.write("		<img src=\"/testKbd/img/img_mando/ase.gif\" width=\"25\" height=\"25\" alt=\"image\">\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">글 번호</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"bnum\" id=\"bnum\" size=\"20\" value=\"");
      out.print( bnum );
      out.write("\" readonly></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">제목</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"bsubject\" id=\"bsubject\" value=\"");
      out.print( bsubject );
      out.write("\" size=\"55\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">이름</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"bwriter\" id=\"bwriter\" value=\"");
      out.print( bwriter );
      out.write("\" size=\"20\" ></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">비밀번호</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"bpw\" id=\"bpw\" value=\"");
      out.print( bpw );
      out.write("\" size=\"20\" ></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">삭제여부</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"deleteyn\" size=\"20\" value=\"");
      out.print( deleteyn );
      out.write("\" disabled></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">입력일</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"insertdate\" size=\"20\" value=\"");
      out.print( insertdate );
      out.write("\" disabled></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">수정일</td>\r\n");
      out.write("	<td><input type=\"text\" name=\"updatedate\" size=\"20\" value=\"");
      out.print( updatedate );
      out.write("\" disabled></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">내용</td>\r\n");
      out.write("	<td>\r\n");
      out.write("	<textarea name=\"bmemo\" id=\"bmemo\" cols=\"50\" rows=\"10\">");
      out.print( bmemo );
      out.write("</textarea>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"tt\">사진</td>\r\n");
      out.write("	<td>\r\n");
      out.write("	<img src=\"/testKbd/fileupload/board/");
      out.print( bphoto );
      out.write("\" border=\"1\" width=\"40\" height=\"50\" alt=\"image\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">\r\n");
      out.write("	<input type=\"hidden\" name=\"ISUD_TYPE\" id=\"ISUD_TYPE\">\r\n");
      out.write("	<input type=\"button\" value=\"수정\" onclick=\"boardUpdate('U')\"/>\r\n");
      out.write("	<input type=\"button\" value=\"삭제\" onclick=\"boardUpdate('D')\"/>\r\n");
      out.write("	<input type=\"button\" value=\"테스트\" onclick=\"boardUpdate('TEST')\"/>\r\n");
      out.write("	<input type=\"reset\" value=\"취소\" />\r\n");
      out.write("	&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<input type=\"button\" value=\"입력\" onclick=\"checkAction('I')\" />\r\n");
      out.write("	<input type=\"button\" value=\"목록\" onclick=\"checkAction('SALL')\">\r\n");
      out.write("</td>\r\n");
      out.write("<tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
