/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-09-02 07:27:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>회원가입 JSP</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>회원가입 jsp </h3>\r\n");
      out.write("<hr>\r\n");
 request.setCharacterEncoding("EUC-KR"); 
      out.write('\r');
      out.write('\n');

	String mname = request.getParameter("mname");
	String mid = request.getParameter("mid");
	String mpw = request.getParameter("mpw");
	String mgender = request.getParameter("mgender");
	String mbirth = request.getParameter("mbirth");
	String mbirth1 = request.getParameter("mbirth1");
	String mbirth2 = request.getParameter("mbirth2");
	String mhp = request.getParameter("mhp");
	String mhp1 = request.getParameter("mhp1");
	String mhp2 = request.getParameter("mhp2");
	String mtel = request.getParameter("mtel");
	String mtel1 = request.getParameter("mtel1");
	String mtel2 = request.getParameter("mtel2");
	String memail = request.getParameter("memail");
	String memail1 = request.getParameter("memail1");
	String memail2 = request.getParameter("memail2");
	String mzonecode = request.getParameter("mzonecode");
	String mroadaddress = request.getParameter("mroadaddress");
	String mroadaddressdetail = request.getParameter("mroadaddressdetail");
	String mgibunaddress = request.getParameter("mgibunaddress");
	String mhobby = request.getParameter("mhobby");
	String minfo = request.getParameter("minfo");
	String mphoto = request.getParameter("mphoto");
	
	System.out.println("mname >>> : " + mname);
	System.out.println("mid >>> : " + mid);
	System.out.println("mpw >>> : " + mpw);
	System.out.println("mgender >>> : " + mgender);
	System.out.println("mbirth >>> : " + mbirth);
	System.out.println("mbirth1 >>> : " + mbirth1);
	System.out.println("mbirth2 >>> : " + mbirth2);
	System.out.println("mhp >>> : " + mhp);
	System.out.println("mhp1 >>> : " + mhp1);
	System.out.println("mhp2 >>> : " + mhp2);
	System.out.println("mtel >>> : " + mtel);
	System.out.println("mtel1 >>> : " + mtel1);
	System.out.println("mtel2 >>> : " + mtel2);
	System.out.println("memail >>> : " + memail);
	System.out.println("memail1 >>> : " + memail1);
	System.out.println("memail2 >>> : " + memail2);
	System.out.println("mzonecode >>> : " + mzonecode);
	System.out.println("mroadaddress >>> : " + mroadaddress);
	System.out.println("mroadaddressdetail >>> : " + mroadaddressdetail);
	System.out.println("mgibunaddress >>> : " + mgibunaddress);
	System.out.println("mhobby >>> : " + mhobby);
	System.out.println("minfo >>> : " + minfo);
	System.out.println("mphoto >>> : " + mphoto);

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
