/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-09-14 06:14:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.kbd.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class bookSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>도서 정보 조회 화면</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	*{\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	fieldset {\r\n");
      out.write("		width: 400px\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	legend {\r\n");
      out.write("		font-size: 1.2em;\r\n");
      out.write("		/*font-weight: bold;*/\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	td {\r\n");
      out.write("		padding: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.attr {\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.align{\r\n");
      out.write("		text-align: left;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function bookUpdate(actionUpdate) {\r\n");
      out.write("		console.log(\"bookUpdate 진입 >>> : \" + cationUpdate);\r\n");
      out.write("		\r\n");
      out.write("		if ('U' == actionUpdate){\r\n");
      out.write("			document.bookUpdateForm.action=\"/testKbd/book?isudtype=UOK\";\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if ('D' == actionUpdate) {\r\n");
      out.write("			document.bookUpdateFrom.action=\"/testKbd/book?isudtype=DOK\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		document.bookUpdateForm.method=\"POST\";\r\n");
      out.write("		document.bookUpdateForm.enctype=\"application/x-www-form-urlencoded\";\r\n");
      out.write("		document.bookUpdateForm.submit();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function checkAction(ectionName) {\r\n");
      out.write("		console.log(\"actionName 진입 >>> : \" + actionName);\r\n");
      out.write("		\r\n");
      out.write("		if ('I' == actionName){\r\n");
      out.write("			location.href=\"/testKbd/kbd/book.html/\";\r\n");
      out.write("		}\r\n");
      out.write("		if ('SALL' == cationName){\r\n");
      out.write("			lcation.href=\"/testKbd/book?isudtype=SALL\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 request.setCharacterEncoding("EUC-KR"); 
      out.write("\r\n");
      out.write("SELECT\r\n");

	Object obj = request.getAttribute("aList");
	if (obj == null) return;
	
	ArrayList<BookVO> aList = (ArrayList<BookVO>)obj;
	int nCnt = aList.size();
	out.println("::: 조회 건수 " + nCnt + "건");
	
	String bnum = "";
	String btitle = "";
	String bauth = "";
	String isbn = "";
	String bcomp = "";
	String bprice = "";
	String bqty = "";
	String bcover = "";
	String deleteyn = "";
	String insertdate = "";
	String updatedate = "";
	
	if(nCnt == 1){
		BookVO bvo = aList.get(0);
		
		bnum =  bvo.getBnum();
		btitle = bvo.getBtitle();
		bauth = bvo.getBauth();
		isbn = bvo.getIsbn();
		bcomp = bvo.getBcomp();
		bprice = bvo.getBprice();
		bqty = bvo.getBqty();
		bcover = bvo.getBcover();
		deleteyn = bvo.getDeleteyn();
		insertdate = bvo.getInsertdate();
		updatedate = bvo.getUpdatedate();
	}
	

      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td calspan=\"2\">\r\n");
      out.write("<font size=\"4\" color=\"blue\">\r\n");
      out.write("	<img src=\"/testKbd/img/img_mando/ase.gif\" width=\"25\" height=\"25\" alter=\"image\">\r\n");
      out.write("BOOK TEST\r\n");
      out.write("</font>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("<hr>\r\n");
      out.write("<fieldset>\r\n");
      out.write("<legend>도서 정보 조회</legend>\r\n");
      out.write("<form name=\"bookUpdateForm\" id=\"bookUpdateForm\">\r\n");
      out.write("<table border=1>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"attr\">도서번호</td>\r\n");
      out.write("	<td><input type=\"text\" id=\"bnum\" name=\"bnum\" class=\"align\" value=\"");
      out.print( bnum );
      out.write("\" readonly /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"attr\">도서명</td>\r\n");
      out.write("	<td><input type=\"text\" id=\"btitle\" name=\"btitle\" class=\"align\" value=\"");
      out.print( btitle );
      out.write("\" readonly /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"attr\">저&nbsp;&nbsp;&nbsp;자</td>\r\n");
      out.write("	<td><input type=\"text\" id=\"bauth\" name=\"bauth\" class=\"align\" value=\"");
      out.print( bauth );
      out.write("\" readonly /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td style=\"letter-spacing: 3px\" class=\"attr\">ISBN</td>\r\n");
      out.write("	<td><input type=\"text\" id=\"isbn\" name=\"isbn\" class=\"align\" value=\"");
      out.print( isbn );
      out.write("\" redinly /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td class=\"attr\">출판사</td>\r\n");
      out.write("	<td><input type=\"text\" id=\"bcomp\" name=\"bcomp\" class=\"align\" value=\"");
      out.print( btitle );
      out.write("\" readonly /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"attr\">단&nbsp;&nbsp;&nbsp;가</td>\r\n");
      out.write("<td><input type=\"number\" id=\"bprice\" name=\"bprice\" class=\"align\" value=\"");
      out.print( bcomp );
      out.write("\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"attr\">수량</td>\r\n");
      out.write("<td><input type=\"number\" id=\"bqty\" name=\"bqty\" class=\"align\" value=\"");
      out.print( btitle );
      out.write("\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"attr\">표지</td>\r\n");
      out.write("<td><input type=\"text\" id=\"bcover\" name=\"bcover\" class=\"align\" value=\"");
      out.print( bcover );
      out.write("\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"attr\">삭제여부</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"mdeleteyn\" id=\"mdeleteyn\" class=\"align\" value=\"");
      out.print( deleteyn );
      out.write("\" disabled  />\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"attr\">등록일</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"minsertdate\" id=\"minsertdate\" class=\"align\" value=\"");
      out.print( insertdate );
      out.write("\" disabled />\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"attr\">수정일</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"mupdatedate\" id=\"mupdatedate\" class=\"align\" value=\"");
      out.print( updatedate );
      out.write("\" disabled />\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td colspan=\"2\">\r\n");
      out.write("		<input type=\"hidden\" name=\"isudtype\" id=\"isudtype\" />\r\n");
      out.write("		<input type=\"button\" value=\"수정\" onclick=\"bookUpdate('U')\" />\r\n");
      out.write("		<input type=\"button\" value=\"삭제\" onclick=\"bookUpdate('D')\" />\r\n");
      out.write("		<input type=\"rest\" value=\"취소\" />\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		<input type=\"button\" value=\"입력\" onclick=\"checkAction('I')\"/>\r\n");
      out.write("		<input type=\"button\" value=\"목록\" onclick=\"checkAction('SALL');\"/>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
